apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docling-serve.fullname" . }}
  labels:
    {{- include "docling-serve.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "docling-serve.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "docling-serve.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "docling-serve.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
        feature.node.kubernetes.io/cpu-cpuid.AVX2: "true"
        {{- if .Values.gpu.enabled }}
        {{- toYaml .Values.gpu.nodeSelector | nindent 8 }}
        {{- end }}
        {{- with .Values.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.port | int }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "docling-serve.fullname" . }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- if .Values.gpu.enabled }}
            requests:
              {{- toYaml .Values.resources.requests | nindent 14 }}
              {{ .Values.gpu.resourceName }}: {{ .Values.gpu.count | quote }}
            limits:
              {{- toYaml .Values.resources.limits | nindent 14 }}
              {{ .Values.gpu.resourceName }}: {{ .Values.gpu.count | quote }}
            {{- else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
